alias home="cd ~/project"
alias build="source ~/project/scripts/colcon_build.sh"
alias teleop="ros2 run teleop_twist_keyboard teleop_twist_keyboard"
alias race="ros2 launch boxbots launch_sim_race.launch.py"
alias arena="ros2 launch boxbots launch_sim_arena.launch.py"
alias slam="ros2 launch slam_toolbox online_async_launch.py params_file:=~/project/src/boxbots/config/mapper_params_online_async.yaml use_sim_time:=true"
alias nav="ros2 launch boxbots navigation_launch.launch.py"
alias rviz_nav="ros2 run rviz2 rviz2 -d ~/project/src/boxbots/config/rviz_slam_with_navigation.rviz"
alias keydb="ros2 run teleop_twist_keyboard teleop_twist_keyboard --ros-args -r __ns:=/donBarredora"
alias keyax="ros2 run teleop_twist_keyboard teleop_twist_keyboard --ros-args -r __ns:=/axeBot"
alias joy1="ros2 launch boxbots joystick0.launch.py"
alias joy2="ros2 launch boxbots joystick1.launch.py"